#+title: Host-pathogen embedded co-genealogies in the context of epidemiology and coevolution 
#+setupfile: ~/.doom.d/setup-files/latex_preview.setup
#+OPTIONS: toc:nil author:nil date:nil

#+LATEX_HEADER_EXTRA: \author[1]{Philip Wolper}
#+LATEX_HEADER_EXTRA: \author[2]{Johannes Müller}
#+LATEX_HEADER_EXTRA: \author[1]{Aurélien Tellier}
#+LATEX_HEADER_EXTRA: \affil[1]{Chair of Population Genetics, Technical University of Munich, Germany}
#+LATEX_HEADER_EXTRA: \affil[2]{Department of Mathematics, Technical University of Munich, Germany}

#+LATEX_HEADER_EXTRA: \addbibresource{~/biblio/pop-gen.bib}


Exploration of the nested Host-Pathogen WF-SI model.
* TODO Host coalescent model with vertical pathogen transmission :noexport: 
- Question: What happens to pathogen coalescence for only vertical transmission with probability $c_v < 1$?
* Epidemic pathogen model betwen host generation
We describe the horizontal epidemiological process $\mathcal{J}_t$ pathogen during host generations $n+1$ as an SI infection model with contact rate $\beta$, occuring for time $G$ as

\begin{equation}
\mathcal{J}_t: \quad J_0  \rightarrow J_G \quad \text{at rate } \beta(N-J_t)J_t/N.
\end{equation}

with intital conditions $\mathcal{J}_0 = I_n+1$ as the number of infected host offspring. The fraction of infected hosts $i(t) = J_t/N$ follows the the ODE

\begin{equation}
\frac{di}{dt} = \beta i(1-i), \quad \text{with } i(0) = J_0/N
\end{equation}

that has the solution

\begin{equation}
i(t) = \frac{i_0}{e^{-\beta t}(1-i_0) + i_0}.
\end{equation}

For one intial infection this system looks like the following: with the number of infected growing faster in time depending on the transmission rate $\beta$.

* Semi-discrete model with vertical and horizontal transmission 
Assuming the number of infected at the end of the generation $n+1$ to be

\begin{equation}
X_{n+1} = I_{n+1} + K_{n+1}
\end{equation}

where $I_{n+1}$ is the number of infected host offspring and $K_{n+1}$ individuals are newly infected due to the epidemiological process $\mathcal{J}_G$ in generation $n+1$.

If we take $N$ to infinity, we get the deterministic limit of the model, and with $x_n = X_n/N$ we have $I_{n+1}/N \approx c_v x_n$. For the stationary solution $x_n = x_{n+1} = x$ we get

\begin{align}
x = x^* &= \frac{c_v - (1 -c_v)e^{-\beta G}}{c^2_v+(1-c_v)c_v(1-e^{-\beta G})} \\
&= \frac{c_v -e^{-\beta G} + c_v e^{-\beta G}}{c_v + c_v e^{-\beta G} + c_v^2 e^{-\beta G}} 
\end{align}

_Boundary conditions_: \\
We wish to understand the boundary conditions for pathogen extinction, as the non-trivial equilibrium above can yield $x^* < 0$. The value of $x^*$ is positive for all positive values of the numerator, as the denominator is positive for all $c_v$, $\beta$ and $G$ greater than 0. As the numerator is positive under $c_v > (1-c_v)e^{-\beta G}$, we get the boundary condition for persistence of the pathogen as

$$c_v > \frac{1}{1+e^{\beta G}}$$

As $\beta G > 0$, the r.h.s is strictly smaller than 0.5, meaning the boundary condition for persistence of the disease is $c_v \ge 0.5$, regardless of how low $\beta G$ become. By the same logic, if the vertical contact rate $c_v < 0.5$, we get the minimum horizontal transmission $\beta G$ required to avoid extinction as

$$\beta G > \ln \left(\frac{1-c_v}{c_v}\right)$$ 

# possibly simplify $\frac{x-y+xy}{x+xy+x^2y}$
** Pairwise coalescent probability
The probability that two randomly sampled pathogen lineages coalesce depends on both hoizontal and vertical transmission. Coalescence can happen either within an epidemic clade deriving from each founding offspring infected (with probability $\pi$) or following host coalescence with vertical transmission in both host infected offspring. In the later case the probability is $1/N$, such that

$$p_c = P(\text{coalescence of two pathogen lineages with one host generation}) = \pi + (1-\pi)\frac{1}{N}.$$

Following the derivation of $\pi$ from a Pólya urn model (see appendix), we obtain
$$\pi = \frac{j}{j+I-1}\frac{2}{I+1}$$.

Expecting $I = Nc_v x^*$ founding infected and $j = Nx^* - I = N(1-c_v)x^*$ newly infecteds, such that in leading order (?)

$$\pi = \frac{N(1-c_v)x^*}{N x^* - 1} \frac{2}{c_v x^* N + 1} \approx \frac{2(1-c_v)}{c_v x^*}\frac{1}{N}$$

the coalescence probability becomes
 
$$p_c\approx \frac{1}{N}\left(1+\frac{2(1-c_v)}{c_vx^*}\right), $$

which become finally after substituting eqn for $x^*$:

$$p_c\approx \frac{1}{N}\left[1+\frac{2(1-c_v)\left[1-(1-c_v)e^{-\beta G}\right]}{c_v-(1-c_v)e^{-\beta G}}\right]$$

** Ancestral process $A_n$
Ancestral process $A_n$ denotes the number of pathogen lineages $n$ generations backwards in time, decreating whenever two lineages coalesce. Suppose you start with $k$ pathogen samples at the present generation, the number of lineages starts  $A_0=k$, and goes through the process $k \rightarrow k-1 \rightarrow k-2 \rightarrow \cdots \rightarrow2 \rightarrow1$. If $N$ is large that higher order terms disappear $p_c = \mathcal{O}(N^{-1}) << 1$, the ancestral process can be defined as 

$$P(A_{n+1}=A_n-1\mid A_n) = p_c {A_n\choose2}$$

gives you the transition probability of the lineage-counting process, from that, you can construct the entire ancestral process:

$$ n \xrightarrow{\lambda_n} n-1 \xrightarrow{\lambda_{n-1}} n-2 \rightarrow \cdots \xrightarrow{\lambda_2} 1.$$

where $\lambda_k$ is the coalescence rate when there are $k$ ancestral lineages.
Suppose there are currently $k$ ancestral lineages. There are ${k\choose2}$ possible pairs, and each pair coalesces with probability $p_c$. Probability of a coalescent event when there are $k$ lineages

$$\lambda_k = p_c {k\choose 2} = p_c\frac{k(k-1)}{2}$$

with waiting times $T_k$ until the next coalescence approximately geometric (?) distributed in continuous time ($A_n = A_t$) following $P(T_k=t\mid A=k) = (1-\lambda_k)^{t-1}\lambda_k$ with $t=1,2, \ldots$, and an expected value of

$$E[T_k] = \frac{1}{\lambda_k} = \frac{2}{p_c k(k-1)}.$$

Define $T_{n}$ as the time backwards to the most recent common ancestor of $n$ samples, where $T_k$ is the waiting time distribution for the process to go from $k$ lineages to $k-1$. The expectation $E[T_n]$ derives from summing over all $T_k$ down to $k=1$ lineage. For a large sample size $n$, we get the following *footnote* where the final equality follows from $\frac{1}{k(k-1)}=\frac{1}{k-1}-\frac{1}{k}$.

\begin{align}
E[T_{n}] &= \sum_{k=2}^n E[T_k] = \frac{2}{p_c}\sum_{k=2}^n\frac{1}{k(k-1)} = \frac{2}{p_c} \left(1-\frac1n\right).
\end{align}

For large $n$, this approaches $E[T_{n}]\approx 2/p_c$.

#+ATTR_LATEX: :options [title=The Wright-Fisher model and Kingman's coalescent]
#+begin_tcolorbox
Below is the derivation of the coalescence times for a haploid Wright-Fisher model if $p_c=1/N$
then
$$
P(A_{n+1}=k-1\mid A_n=k)
\simeq \frac{k(k-1)}{2N}.
$$
and
$$
E[T_k]=\frac{2N}{k(k-1)}.
$$
The time to the most recent common ancestor becomes:
$$E[T_n] = 2N\left(1-\frac1n\right).$$
And for large sample size $n$, this is the familiar Kingman coalescent result.
$$E[T_{n}]\approx 2N.$$
#+end_tcolorbox
* Python code and plots :noexport:
#+begin_src python :session :results value :exports none
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import itertools
#+end_src


** SI process
#+begin_src python :session :results output :exports none 
N = 1000 # Host population size
betas = [0.1, 0.3, 0.5, 1] # contact rate
G = 50
t = np.linspace(0, G, 100) # time from 0 -> G
i_0 = 0.4

def SI_process(t, N, beta, i_0):
    i_t = i_0 / (np.exp(-beta * t)*(1 - i_0) + i_0)
    return(i_t)
#+end_src

#+RESULTS:

#+begin_src python :session :results output :exports none :eval no-export
plt.figure(figsize=(5, 4))

for beta in betas:
    i_t = SI_process(t, N, beta, i_0)
    plt.plot(t, i_t, label=f'$\\beta = {beta}$')

# 4. Apply standard formatting
plt.xlabel('Time (t)')
plt.ylabel('Infected Individuals I(t)')
plt.title('SI Model Trajectories for Different Transmission Rates ($\\beta$)')
plt.legend()
plt.grid(True)
plt.savefig("SI_model_solutions.pdf", bbox_inches='tight', dpi=300)
#+end_src

#+RESULTS:

** Equilibrium $^*$
#+begin_src python :session :results output :exports none :eval no-export
cVs = [1, 0.75, 0.5, 0.25, 0.1] # probability of vertical transmission
betas = [0.05, 0.1, 0.3, 0.5, 1] # contact rate
Gs = [1, 5, 10, 20, 50] # epidemic time

cV_cont = np.linspace(min(cVs), max(cVs), 100)
beta_cont = np.linspace(min(betas), max(betas), 100)
G_cont = np.linspace(min(Gs), max(Gs), 100)

# Deterministic approximation
def x_equilibrium(cV,beta, G):
    x = (cV-(1-cV)*np.exp(-beta*G))/(cV**2+(1-cV)*cV*(1-np.exp(-beta*G)))
    return(x)
#+end_src

#+RESULTS:

#+begin_src python :session :results output :exports none :eval no-export
data = []
for cV, beta, G in itertools.product(cVs, betas, Gs):
    x_star = x_equilibrium(cV, beta, G)
    data.append({'cV': cV, 'beta': beta, 'G': G, 'x_star': x_star})

df = pd.DataFrame(data)
print(df)
#+end_src

#+RESULTS:
#+begin_example
     cV  beta   G    x_star
0   1.0   0.1   1  1.000000
1   1.0   0.1   5  1.000000
2   1.0   0.1  10  1.000000
3   1.0   0.1  20  1.000000
4   1.0   0.1  50  1.000000
..  ...   ...  ..       ...
95  0.1   1.0   1 -3.454755
96  0.1   1.0   5  0.945090
97  0.1   1.0  10  0.999632
98  0.1   1.0  20  1.000000
99  0.1   1.0  50  1.000000

[100 rows x 4 columns]
#+end_example

#+begin_src python :session :results output :exports none :eval no-export
g1 = sns.relplot(
    data=df, kind="line",
    x="G", y="x_star", hue="beta", col="cV",
    palette="viridis", marker=None, height=3.5, aspect=1
)
g1.fig.suptitle('Equilibrium ($x^*$) vs Epidemic Time (G)', y=1.05)
plt.show()
#+end_src

#+RESULTS:

*** Heatmaps (not working...)

The following plots show how $x^*$ behaves in relation to $\beta$, $G$ and $c_V$ based on the above deterministic limit. Improve heatmaps to regular cline plots and $x^*$?

#+begin_src python :session :results graphics file value :exports results :file xheatmap_beta_G_per_cV.pdf :eval no-export
beta_grid, G_grid = np.meshgrid(beta_cont, G_cont)
Xs = [x_equilibrium(cV, beta_grid, G_grid) for cV in cVs]

fig, axes = plt.subplots(1, len(cVs), figsize=(4*len(cVs), 3), sharey=True, layout='constrained')

for i, (cV, x) in enumerate(zip(cVs, Xs)):
    ax = axes[i]
    
    im = ax.pcolormesh(G_grid, beta_grid, x, cmap='viridis', shading='auto', vmin=0, vmax=1)
    ax.set_title(rf'$c_V = {cV}$')
    ax.set_xlabel(r'$G$')
    ax.set_ylabel(r'$\beta$')

fig.colorbar(im, ax=axes.ravel().tolist(), label=r'$x^*$')
# plt.gcf()
#+end_src

#+attr_latex: :width \textwidth
#+RESULTS:
[[file:xheatmap_beta_G_per_cV.pdf]]

#+begin_src python :session :results graphics file value :exports results :file xheatmap_G_cV_per_beta.pdf :eval no-export
G_grid, cV_grid = np.meshgrid(G_cont, cV_cont)
Xs = [x_equilibrium(cV_grid, beta, G_grid) for beta in betas]

fig, axes = plt.subplots(1, len(betas), figsize=(4*len(betas), 3), sharey=True, layout='constrained')

for i, (beta, x) in enumerate(zip(betas, Xs)):
    ax = axes[i]
    
    im = ax.pcolormesh(G_grid, cV_grid, x, cmap='viridis', shading='auto', vmin=0, vmax=1)
    ax.set_title(rf'$\beta = {beta}$')
    ax.set_xlabel(r'$G$')
    ax.set_ylabel(r'$c_V$')

fig.colorbar(im, ax=axes.ravel().tolist(), label=r'$x^*$')
# plt.gcf()
#+end_src

#+attr_latex: :width \textwidth
#+RESULTS:
[[file:xheatmap_G_cV_per_beta.pdf]]

#+begin_src python :session :results graphics file value :exports results :file xheatmap_beta_cV_per_G.pdf :eval no-export
beta_grid, cV_grid = np.meshgrid(beta_cont, cV_cont)
Xs = [x_equilibrium(cV_grid, beta_grid, G) for G in Gs]

fig, axes = plt.subplots(1, len(Gs), figsize=(4*len(Gs), 3), sharey=True, layout='constrained')

for i, (G, x) in enumerate(zip(Gs, Xs)):
    ax = axes[i]
    
    im = ax.pcolormesh(beta_grid, cV_grid, x, cmap='viridis', shading='auto', vmin=0, vmax=1)
    ax.set_title(rf'$G = {G}$')
    ax.set_xlabel(r'$\beta$')
    ax.set_ylabel(r'$c_V$')

fig.colorbar(im, ax=axes.ravel().tolist(), label=r'$x^*$')
# plt.gcf()
#+end_src

#+attr_latex: :width \textwidth
