#+title: BarleyCOPA Progress Report 2025 - WP1
#+setupfile: ~/.doom.d/setup-files/latex.setup
#+options: toc:nil date:nil title:nil num:nil  

# #+bibliography: ~/biblio.pop-gen.bib
#+LATEX_HEADER: \addbibresource{~/biblio/pop-gen.bib}
** Progress reproting WP1.2 - Philip Wolper (PhD student)
In anticipation of the data aquisition phase the efforts of our work for WP1 has centered around developing the theoretical framework necessary to analyze and interpret host and pathogen genomic data. 
As there is currently no generalized framework of how host and pathogen coevolution gives rise to ancestral genealogies across their respective genomes it has been a major focus of ours to develop such a theoretical framework. This is necessary because modern high-throughput population sequencing technologies allow us to generate large amounts of data, which has caused a paradigm shift in modern population genomics focusing more on the evolutionary histories on the genome (genealogy-based) than the classic site-based approach which focuses on individual DNA mutations ([[cite:&ralph-2020-effic-summar]]).
Carried by algorithmic and computational advances of inferring and simulating genome-wide ancestries (ancestral recombination graphs, ARG), the genealogical approach promises to provide a model-based, complete evolutionary picture of genomic data, that does not rely on summary statistics. Additionally a theory of host-pathogen co-genealogies could allow us to connect host-pathogen evolution to established theory and methods of phylodynamics, which use trees and genealogies to infer pathogen epidemiological dynamics. Thus, we expect such phylodynamics inference can be extend from epidemic to coevolutionary settings and single phylogenies to recombining genealogies.

At the time of this progress reporting we have successfully developed a generalized stochastic model of coevolution, that describes the genomic ancestral histories of both host and pathogens. We refer to our model as a host-pathogen nested Canning's model, and it includes the possibility for horizontal and vertical transmission. Currently we are actively collaborating with several mathematicians (including Johannes Müller, Department of Mathematics at TUM; Cornelia Pokalyuk, Uni Lübeck and Fabian Freund, University of Leicester, UK) in order to further understand the properties of our model from a mathematical perspective. Additionally we have begun to implement our model in the genomic simulation framework SLiM ([[cite:&haller-2019-tree-recor]]), and are exploring the behaviour of simulated host and pathogen genealogies under different coevolutionary and epidemiological scenarios.

We anticipate that this work will lead to the identification of robust genomic summaries that represent the coevolutionary process at both the level of genealogies and sites. Further we plan on using Approximate Bayesian Computation to identify parameters of our model from simulations. We hope that in the future these theoretical advances can be applied to ARGs inferred from host and pathogen DNA data to develop novel methodologies linking ARGs and epi-eco-evolutionary processes. More specifically, once we have collected data of /Fusarium/ and /Ramularia/ from the field trials we will work on how to apply this (co-)genealogical approach to Barley and two of its important pathogens.  It it conceivable that this may lead to novel insights on this specific host-pathosystem, as well as more generally into other systems.
 
In addition to our progress in our work, we have been actively taking part in the scientific community, by seeking collaborations within our own and other institutions and attending scientific conferences to share and discuss our results. Since the project funding began, we have attended conferences in Munich (EvoGen Munich, March 2025 and '26), in Kenya (CoNeMesSA, Sep. 2025, expenses funded by CoNeMesSA project funds and Prof. Johannes Müller, TUM) on disease modeling and epidemiology, as well as attended the 'Annual Meeting of Plant Research funded by the BMFTR' (Postdam, March 2026) to share updates on the BarleyCOPA project. Planned conferences for the next period of research are the Jaques Monod Conference on the /Ecology and Evolution of host-parasite interaction in a changing world/ in Roscoff, France (Nov. 2026).

[[printbibliography:]]
