#+title: Inferring coevolutionary interaction from a coalescent perspective
#+author: Philip L. Wolper

#+setupfile: ~/.doom.d/setup-files/latex.setup
#+OPTIONS: toc:nil num:nil
#+LATEX_HEADER: \addbibresource{~/biblio/pop-gen.bib}


We want to investigate the joint behaviour of genealogies in coevolving species of host-parasite interactions. Describing the dynamics of coevolution at the level of genomic coalescence trees, our aims is to better understand the sigantures coevolution leaves in the genomes of interacting species to improve inference of both functional, quantitative GxG interactions, as well as population genetic information such as demographic and reproductive life-histories of both species.\\

** Questions and Aims
We want to investigate the joint behaviour of genealogies in coevolving species of host-parasite interactions. Describing the dynamics of coevolution at the level of genomic coalescence trees, our aims is to better understand the sigantures coevolution leaves in the genomes of interacting species to improve inference of both functional, quantitative GxG interactions, as well as population genetic information such as demographic and reproductive life-histories of both species.\\
*** How can we describe the co-dependence of host and pathogen genealogies?
As we know the pairings of hosts and pathogens (through time), can find a measure of correlations between the 'aligned' host and pathogen genealogies?  Above average appearance of host and parasite types together in pairwise nodes of the co-dependent genealogies? How will different statistical measures of the trees (eg. TMRCA and tree topology) be correlated in various co-evolutionary scenarios?  Relative importance of TMRCA vs. topology? Significant deviations from neutral 'co-evolutionary' signatures between indicate co-evolution (what does 'neutral' co-evolution mean?). The 'neutral' co-evolutionary model needs account for neutrality, linkage disequilibrium, life-history traits as well as demographic history.

*** Coalescent models used need to be descriptive of the co-evolutionary dynamics at play.
This might require coalescents other than Kingman's coalescent. Depending on life-history the host and pathogen might require different reproductive models, which give rise to the sample genealogy. For example, Wright-Fisher reproduction in host (or neutral agricultural sowing scheme) and sweepstakes reproduction in pathogens? Comparison of coalescent trees should be independent of coalescent model used to construct the sample genealogy, so to give freedom to model life-history and epidemiology. What role does the chosen epidemiological model have on the coalescent process used? Significance of multiple-merger coalescent in the spread of disease and epidemiological descriptions (see work on multifurcating skyline plot, [[cite:&hoscheit-2019-multif-skylin-plot]])? Can we connect the model of co-evolution to the multiple merger dynamics of skewed pathogen offspring distributions?  What is the relation of the forward (eg. disease dynamics) and backwards models (host and pathogen coalescents)? What information does the model of disease dynamics hold towards to description of coalescent genealogies of hosts and parasites?

*** Can co-dependent genealogies predict the interaction matrix of a genome-genome interaction?
Measure of correlations between genealogies between species should be able to predict the interaction matrix of a genome-genome interaction? Do different types of coalescent models fit to different scoevolutionary scenarios (eg. multiple merger to arms race, etc.)? Do different types co-dependent coalescent signatures fit to different co-evolutionary scenarios such as GFG/MA and how do they differ from the neutral case. Can we connect the epidemiological parameters of a pathogen to it's reproductive Canning's model/coalescent parameters? How do we choose coalescent model to use then? How do such coalescent behaviour reflect back on the epidemiologcal process of the pathogen?

*** How can this work be used improve co-evolutionary inference?
Improving the accuracy of the co-GWAS and the ABC computations to predict genomic regions of interactions? Extension of ABC statistics? We are looking to understand the genomic signatures of co-evolution from a comprehensive (tree-based) perspective, to improve existing inference of GxG interactions. Can we learn anything new about co-evolutionary interaction at the genomic level in the process? How can the coalescent-driven description of host-pathogen genealogies improve epidemiological modelling of diseases (eg. inferring more accurate reproductive parameters or dating transmission chains)?
** Relevance
Previous work has focused much on phylodynamic inference of trees/genealogies of pathogen sequences informed by a dynamic model of disease, such as SIR models (Volz? Rambaut?, etc.?) or linear birth-death processes (Stadler?). This type of analysis is generally focused on short to medium time-scales such as epidemic dynamics of pathogens with the goal of inferring epidemiological parameters from genomic sequences of pathogens. As the times scales are short, phylodynamics generally involves one type of pathogen and and a set of host types (i.e. susceptible, resistant).
On the other hand, there is a large body of work on host-parasite coevolution, focusing more on the long-term evolutionary change of hosts and their parasite, due to reciprocal adaptation.


Separation of literature on phylodynamics and of host-pathogen coevolution, even though both make use of models of disease epidemiology. Why? Phylodynamic-based models of coevolution could help with developing co-genomic perspective of coevolution? Why does the infection matrix disappear when moving to phylodynamics work at the epidemiological timescale?
** Connecting coalescent models to epidemiology
- Offspring distributions from epidemiologcal models: negative binomial ([[cite:&lloyd-smith-2005-super-effec]]) with the parameters $R_{0}$ and $k$.
- [[cite:&li-2017-quant-trans]] show that the dispersion paramter of the epidemiological offspring distribution $k$ can be estimated from the pathogen phylogeny, using a formulation of of the Kingman coalescent with arbitrary offspring distributions ($N_{e} = N/\sigma^{2}$,[[cite:&koelle-2011-rates-coales]], [[cite:&fraser-2017-coales]]). How valid is this assumption for MMC?
- Multifurcating skyline plot [[cite:&hoscheit-2019-multif-skylin-plot]] uses Beta-coalescent to infer the effective population size through time, and show that the estimation of \alpha correlates with the degree of superspreading $k$ in an epidemiological model. What is the direct connection between \alpha and $k$?
- Special Issue: *Next-generation molecular and evolutionary epidemiology of infectious disease*.  https://royalsocietypublishing.org/toc/rstb/368/1614
- Pathogen genealogy inference framework from structured Markov processes (eg. SIR type stochastic models). Aaron King https://arxiv.org/abs/2405.17032#
- From simulations of SIR we can follow genealogy of host, or analytically for pathogen too it we know the AISG (?). Is this useful in downstream analysis (eg. tskit? adding contact arrows, etc.). Is the intrisic presence of the pathogen in the R status of the SIR model enough to work with the pathogen genealogy, or would a two species model be more practical?
- steady states of the SIR model might be reflected in heights of the coalescent trees pathogen/host? Metric from [[cite:&welch-2005-integ-geneal-epidem]]. Expected relative difference betwwen host and viral tree root age and Proportion in common between viral and host trees? Extend results of [[cite:&welch-2005-integ-geneal-epidem]] to resistant classes as well?

** SIR host model
- host classes and frequencies and determining reproductive process of hosts. (might not need for agricultural application, ABC).
- Differential reproduction of infected and non infected host classes (I and S,R?). Propagation of infection tags through the population, linking parasite individual to this host individual. Different parasite classes? Scale fitness of host by parasite virulence factor. Fitness in hosts? Tied to parasite trait? Add interaction matrices?

** Considerations for the two Species model
- how to handle fitness of infected vs. non-infected and resistant host types vs. susceptible host types.
- Ensure model can form equilibrium as observed for SIR model classes or similar.
- Variable population sizes to follow coevolutionary dynamics.

*** Horizontal vs. vertical transmission of pathogen
- How are the genealogies coupled for these different transmission types? Degree of coupling depends on transmission rate?
- *Hypothesis:* Vertical transmission, pathogen genealogy will mirror the topology of the host genealogy. Horizontal tranmission will lead to the topology being different, as the pathogen can jump between lineages.
*** Timescales of reproduction
- *Host vs. pathogen reproduction.* Degree of generation overlap (WF vs. Moran continuum)? Scaling of time (speed/tick modulo) in forward simulations? Genetic drift in host vs. pathogen?
- *Pathogen reproduction vs. transmission.* Drift introduced by transmission? Generation of pathogen offspring seperated from transmission process?
- *Host drift vs. pathogen transmission.* Lineage pathogen can be transmitted through the hos genelogy is influenced by the drift of the host.
- Modelling host and pathogen fitness. Selection on viability or mortality of host/pathogen? Host: infection, cost of resistance. Pathogen: infectivity, cost of infectivity.
*** Infection Matrix
- Infection matrix to incorporate the specific architecture of coevolutionary interaction. Multiple types of pathogen. Allow recombination between different types.

** Patterns of coevolution in co-dependent genealogies
*** Hypothesis
- Coalescent tree of pathogen, scales with the contact rate/ transmission rate? Show with equilibrium of host pathogen dynamics? Results of [[cite:&zivkovic-2019-neutr-genom]]. Coalescence in both genealogies is dependent on the relative time-scale of genetic drift in both the host and the pathogen?
- add table for different cases of host-pathogen models. (eg. vertical/horizontal transmission, timescale of host vs. pathogen, etc.)
*** Cophylogeny
- Inspiration from cophylogentic methods:
  - https://www.cell.com/action/showPdf?pii=S0169-5347%2806%2900378-8
  - https://www.annualreviews.org/content/journals/10.1146/annurev-ecolsys-102320-112823
  - https://academic.oup.com/cz/article/62/4/393/1745416?login=false
  - https://nph.onlinelibrary.wiley.com/doi/10.1111/nph.12150
  - https://onlinelibrary.wiley.com/doi/full/10.1111/j.1420-9101.2007.01340.x
  - https://www.numericalecology.com/Reprints/ParaFit_paper.pdf



* Further thoughts
First, we need a basic model to describe the interaction of host and pathogen genealogies and study 'neutral' forces involved (i.e. constant population size, etc). How would we describe the infectivity/prevalence from the coalescent tree? Higher infectivity and increased transmission would result in a kind of offspring skew, because of higher fitness and more spores/offspring produced. Can we describe this offspring skew as a multiple merger genealogy. Then we are looking for local multiple merger signatures in the genome of pathogens, as a signal of a gene conferring a advantage contributing to it's increased spread (or any signal of positive selection in this sense). How do we know the selection is the result of coevolution (i.e. is associated with a variant in the host)? If this multiple merger siganture is still detectable in the pathogen genealogy, if we sample only pathogens found in the host carrying the variant, and not in the pathogens found in other variants, this means the selective advantage is only conferred by this particular host variant?

[[printbibliography:]]
