#+title: Understanding host-pathogen interactions and (co-)evolution through coalescent genealogies and ancestral recombination graphs
#+subtitle: Abstract for Jaques-Monod Conference /'Ecology and evolution of host-parasite interactions in a changing world'/, Roscoff 2026
#+setupfile: ~/.doom.d/setup-files/latex.setup
#+OPTIONS: toc:nil author:nil
#+LATEX_HEADER: \addbibresource{~/biblio/pop-gen.bib}
#+LATEX_HEADER: \author[1]{Philip Wolper}
#+LATEX_HEADER: \affil[1]{Chair of Population Genetics, Technical University of Munich, Germany}

Host-pathogen coevolutionary systems are shaped by a complex interplay of epidemiological, ecological and evolutionary processes. Disease transmission, recovery and population dynamics of hosts and pathogens interact with mutation, selection, recombination and genetic drift to generate feedbacks that operate across multiple timescales and affect the resuling pattern of inheritance. More specifically, the way coevolution of hosts and pathogens in the context of epidemiological spread and infection dynamics shape the ancestral geneaogical trees of hosts and pathogens (along their genomes) remains poorly understood, as genealogical considerations of complex coevolutionary models has been limited. 
Understanding the ancestral behaviour of host and pathogen lineages promises to provide a model-based evolutionary picture of genomic data, based on the the repoductive processes of the host and the parasite, and the infection process that connects them. Combined with recent advances in simulating ancestral recombination graphs (ARGs) under complex models, this opens the door to improved inference of evolutionary and epidemiological processes from data, such as the type of genetic interaction or epidemiological and demographic parameters.

We develop a stochastic individual-based model of host and pathogens with discrete, non-overlapping generations forwards in-time to model the joint genealogies of hosts and pathogens explicitly. We implement this model using a two-species model in SLiM 5 ([[cite:&haller-2023-slim]]), using tree-sequence recording to track the ARGs of hosts and pathogens. Using this model, we investigate the effects different epidemiological dynamics and transmission modes (eg. vertical, horizontal, super-spreading) have on the joint properties of the host and pathogen genealogies. As we model host and (horizontal) pathogen reproduction seperately from each other our model is able to scale between epidemiological and cevolutionary time scales, by changing the relative speed at with these processes occur on, allowing us to model polycyclic coevolution. Furthermore, we use our model to investigate the effects of different coevolutionary parameters, such as the infection matrix (which determines the infectivity of pathogen types on host types), as well as the effect of costs of infection and resistance on the resulting ancestral host-pathogen histories. By simulating complete evolutionary ancestries of complex coevolutionary and epidemiological models, we anticipate an improved understanding of the genomic signatures in host-pathogen interactions and an improvement in simulation-based inference methods.

We present a theoretical framework for a host-pathogen coevolutionary model with explicit transmission dynamics, that models the joint ancestral genealogies along the genome in hosts and pathogens. Our aim is to provide a perspective of coevolution, inspired by existing tree-based phylodynamic approaches to link pathogen genealogical trees to epidemiological dynamics. Treating hosts and pathogen in terms of joint ARGs, can help phylodynamic methods move from single phylogenies to recombining genomes and accomodate long-term evolutionary dynamics of hosts in addition to the epidemiological dynamics traced by the pathogen genealogies. Furthermore, we discuss our framework in relationship to existing phylogenetic methods, testing for co-speciation and associations in host and pathogen species trees, as statistical tools to analyze associations in pyhlogenetic trees have to potential to be applied to genealogies. We anticipate our genealogical approach to host-pathogen coevolution to act as a connecting piece between tree-based methods at the ecological (phylodynamics) and macroevolutionary (co-speciation) level.  
 
[[printbibliography:]]
