#+title: Understanding host-pathogen interactions and (co-)evolution through joint coalescent genealogies
#+subtitle: Abstract for Jaques-Monod Conference /'Ecology and evolution of host-parasite interactions in a changing world'/, Roscoff 2026
#+setupfile: ~/.doom.d/setup-files/latex.setup
#+OPTIONS: toc:nil author:nil
#+LATEX_HEADER: \addbibresource{~/biblio/pop-gen.bib}
#+LATEX_HEADER: \author[1]{Philip Wolper}
#+LATEX_HEADER: \author[2]{Johannes Müller}
#+LATEX_HEADER: \author[1]{Aurélien Tellier}
#+LATEX_HEADER: \affil[1]{Chair of Population Genetics, Technical University of Munich, Germany}
#+LATEX_HEADER: \affil[2]{Department of Mathematics, Technical University of Munich, Germany}

* Abstract
Host-pathogen coevolutionary systems are shaped by a complex interplay of epidemiological, ecological and evolutionary processes. Disease transmission, recovery and population dynamics of hosts and pathogens interact with mutation, selection, recombination and genetic drift to generate feedbacks that operate across multiple timescales and affect the resuling pattern of inheritance. Coevolutionary interactions involving reciprocal, frequency-dependent selection and fitness costs are affected by epidemiological feedback and ecological time scales. A large body of theoretical work exists on coevolution, typically focusing on solutions and equilibrium in continuous or discrete mdoels of coevolution, successfully describing many complex models ([[cite:&buckingham-2022-coevol-theor]]). 
It is however less understood, how coevolutionary interactions specifically shape the respective host and pathogens ancestral genealogical trees along their genomes (ancestral recombination graphs, ARGs) in the context of epidemiological spread and infection dynamics.
While phylodynamics provides recent generalizations of eidemiological dynamics as coalescent processes ([[cite:&didelot-2025-ances-proces]]), similar coalescent-based considerations of coevolutionary models have been limited so far (with exception of [[cite:&welch-2005-integ-geneal-epidem]]), despite recent advances simulating ARGs and tree sequences ([[cite:&jeffery-2026-popul-ances]]).

In this work we derive coalescence properties for of a pathogen embedded through vertical and horizontal transmission in a host genealogical process. We develop a semi-discrete stochastic model of host and pathogens with discrete, non-overlapping host reproduction and vertical and horizontal transmission of a pathogen between and within host generations, respectively. This model represents a pathogen, transmitted between generations and developing as epidemic cycles within host generations, such as the case for seasonal plant diseases and other semi-discrete host-pathogen host systems. Our model builds upon the Wright-Fisher model, except with an embedded time-continuous infection model, and thus remains ammendable to much established population genetics theory, including models of frequency-dependent selection ([[cite:&tellier-2021-theor-host]]). Using deterministic approximations of the stochastic host and pathogen processes we derive pairwise coalescence probabilities for pathogens embedded in the host colescence tree through vertical transmission.
We show how pathogen coalescence is jointy affected by host coalescence and the epidemic process, dependent on the rate of vertical transmission $c_v$, the epidemiological contact rate $\beta$ and the length of the epidemic outbreak $G$.
To study stochastic effects and properties of joint host-pathogen ancestral trees (co-ARGs) for more than two samples, we implement this model using a two-species model in SLiM 5 ([[cite:&haller-2023-slim]]), using tree-sequence recording to track the ARGs of hosts and pathogens, allowing us to model the joint genealogies of hosts and pathogens explicitly forward in-time.

In future work, we wish to we investigate the effects different epidemiological dynamics and transmission modes (eg. SIS, super-spreading) have on the joint properties of the host and pathogen genealogies. Additionally, we aim to extend our framework to more complex models of coevolution, including frequency-dependent selection and fitness costs within multiple types of hosts and pathogens, allowing for genetic interaction matrices common to coevolution.  
By investigating the behviour of these joint genealogies under more complex coevolutionary and epidemiological models, we anticipate an improved understanding of the genomic signatures in host-pathogen interactions ([[cite:&ebert-2020-host]]), better simulation-based inference methods ([[cite:&maerkle-2024-infer-host]]). We also discuss statistical methods of cophylogenetic host-pathogen species tree associations and how they could be applied to coevolutionary genealogies.
Generally, we aim to provide a perspective of coevolution, inspired by existing tree-based approaches (such as phylodynamics, [[cite:&plessis-2015-gettin-to]] or co-pylogenetics, [[cite:&dismukes-2022-cophy-method]]) and coalescent theory to explain joint host and pathogen genealogical processes.
We hope, that formalizing coevolutionary interactions in the context joint genealogies could help connect such different tree-based methods across scales of host-pathogen interactions, including epidemiologiy, coevolution and speciation.

[[printbibliography:]]

* Abstract long :noexport:
Host-pathogen coevolutionary systems are shaped by a complex interplay of epidemiological, ecological and evolutionary processes. Disease transmission, recovery and population dynamics of hosts and pathogens interact with mutation, selection, recombination and genetic drift to generate feedback that operate across multiple timescales and affect the resulting pattern of inheritance. Coevolutionary interactions involving reciprocal, frequency-dependent selection and fitness costs are affected by epidemiological feedback and ecological time scales. A large body of theoretical work exists on coevolution, typically focusing on solutions and equilibrium in continuous or discrete models of coevolution ([[cite:&buckingham-2022-coevol-theor]]), successfully describing many complex coevultionary processes.
However, it is less understood, how coevolutionary interactions specifically shape the respective host and pathogens ancestral genealogical trees along their genomes (ancestral recombination graphs, ARGs) in the context of epidemiological spread and infection dynamics, as coalescent-based considerations of complex coevolutionary models have been limited so far (with exception to [[cite:&welch-2005-integ-geneal-epidem]]), despite recent advances simulating ARGs and tree sequences ([[cite:&jeffery-2026-popul-ances]]).

In this work we derive coalescence properties for of a pathogen embedded through vertical and horizontal transmission in a host genealogical process. We develop a semi-discrete stochastic model of host and pathogens with discrete, non-overlapping host reproduction and vertical and horizontal transmission of a pathogen between and within host generations, respectively. This model represents a pathogen, transmitted between generations and developing as epidemic cycles within host generations, such as the case for seasonal plant diseases and other semi-discrete host-pathogen host systems. Our model builds upon the Wright-Fisher model, except with an embedded time-continuous infection model, and thus build upon common population genetics theory. Using deterministic approximations of the stochastic host and pathogen processes, we derive pairwise coalescence probabilities for pathogens embedded in the host colescence tree through vertical transmission.
We show how pathogen coalescence is jointy affected by host coalescence and the epidemic process, dependent on the rate of vertical transmission $c_v$, the epidemiological contact rate $\beta$ and the length of the epidemic outbreak $G$.
# Interestingly, as our model is semi-discrete, we can scale the relative speed of host and pathogen process, by adjusting the length of the epidemiologcal process $G$ relative to the host population size $N$, representing the contribution of both coevolutionary and epidemiological time scales.
To study stochastic effects and propoerties of joint host-pathogen ancestral recombination graphs (co-ARGs) for more than two samples, we implement this model using a two-species model in SLiM 5 ([[cite:&haller-2023-slim]]), using tree-sequence recording to track the ARGs of hosts and pathogens, allowing us to model the joint genealogies of hosts and pathogens explicitly forward in-time.

In future work, we wish to we investigate the effects different epidemiological dynamics and transmission modes (eg. SIS, super-spreading) have on the joint properties of the host and pathogen genealogies. Additionally, a goal of ours is to extend our framework to coevolution, including propoerties such as frequency-dependent selection and fitness costs, as well as multiple types of host-pathogens, allowing for genetic intereaction matrices.
Another extension, could be generalizing the discrete host process to a overlapping generations, such as derived by [[cite:&alexandre-2025-bridg-wrigh]].
By investigating the joint host and pathogen ancestral genealogies under of more complex coevolutionary and epidemiological models, we anticipate an improved understanding of the genomic signatures in host-pathogen interactions ([[cite:&ebert-2020-host]]), better simulation-based inference methods ([[cite:&maerkle-2024-infer-host]]), as well more powerful phylodynamic methods ([[cite:&plessis-2015-gettin-to]]).

# Improving the understanding of the ancestral processes of host and pathogen lineages promises to improve our model-based coevolutionary picture of  host pathogen genomes, based on the the repoductive processes of the host and the parasite and the infection process that connects them.
# Combining coalescent theoretical approaches of host-pathogen systems with recent advances in the forward-simulation of ancestral recombination graphs (ARGs) under complex models, opens the door to improved inference of evolutionary and epidemiological processes from data, such as the genetic interaction matrix ([[cite:&maerkle-2024-infer-host]]) or epidemiological and demographic parameters.
# In summary, we present a theoretical framework for a host-pathogen coevolutionary model with explicit transmission dynamics, that models the joint ancestral genealogies along the genome in hosts and pathogens.
In summary we wish to provide a perspective of coevolution, inspired by existing tree-based phylodynamic approaches ([[cite:&featherstone-2022-epidem-infer]]) and coalescent theory to explain joint host and pathogen genealogical processes.
# Treating hosts and pathogen in terms of joint ARGs, can help phylodynamic methods move from single phylogenies to recombining genomes and accomodate long-term evolutionary dynamics of both species in addition to the epidemiological dynamics traced by the pathogen genealogies.
Finally, we discuss using existing cophylogenetic methods and statistical tools of cospeciation and host-pathogen species tree associations, and their applications to genealogies. We hope, that formalizing coevolutionary interactions as joint genealogies could help connect different tree-based methods used at epidemiological, ecological, evolutionary and co-speciation levels.
 
[[printbibliography:]]
